INSERT OR IGNORE INTO `menu_items` (`id`,`category_id`,`name`,`description`,`price_cents`,`available`,`customizable`) VALUES
('burger-lebanese','burger-sandwich','Burger lebanese','',500,1,1),
  ('burger-classic-cheese','burger-sandwich','Burger classic cheese','',600,1,1),
  ('chicken-burger','burger-sandwich','Chicken burger','',500,1,1),
  ('zinger-cheese','burger-sandwich','Zinger cheese','',600,1,1),
  ('sandwich-crispy','sandwich','Crispy','',500,1,1),
  ('sandwich-chicken-sub','sandwich','Chicken sub','',500,1,1),
  ('sandwich-twister','sandwich','Twister','',500,1,1),
  ('sandwich-francisco','sandwich','Francisco','',500,1,1),
  ('sandwich-tawouk','sandwich','Tawouk','',500,1,1),
  ('sandwich-fries','sandwich','Fries','',300,1,1),
  ('sandwich-escalope','sandwich','Escalope','',500,1,1),
  ('sandwich-chicken','sandwich','Chicken','',500,1,1),
  ('sandwich-roasto','sandwich','Roasto','',500,1,1),
  ('sandwich-roasto-cheese','sandwich','Roasto & cheese','',600,1,1),
  ('sandwich-sujuk','sandwich','Sujuk','',500,1,1),
  ('sandwich-sujuk-cheese','sandwich','Sujuk & cheese','',600,1,1),
  ('sandwich-makanik','sandwich','Makanik','',500,1,1),
  ('sandwich-nkhaat','sandwich','Nkhaat','',500,1,1),
  ('sandwich-sanasel','sandwich','Sanasel','',500,1,1),
  ('sandwich-lsenet-ghanam','sandwich','Lsenet ghanam','',600,1,1),
  ('sandwich-lsenet-baar','sandwich','Lsenet baar','',600,1,1),
  ('sandwich-zinger-club-special','sandwich','Zinger club special','',700,1,1),
  ('sandwich-kafta','sandwich','Kafta','',500,1,1),
  ('sandwich-kafta-cheese','sandwich','Kafta & cheese','',600,1,1),
  ('sandwich-crab','sandwich','Crab','',500,1,1),
  ('sandwich-cocktaillo','sandwich','Cocktaillo','',700,1,1),
  ('appetizer-fries-box','appetizers','Fries box','',400,1,0),
  ('appetizer-nuggets-box','appetizers','Nuggets box','',600,1,0),
  ('appetizer-bob-court-box','appetizers','Bob court box','',600,1,0),
  ('appetizer-mazorella-sticks','appetizers','Mazorella sticks','',600,1,0),
  ('salad-chicken-cesar','salad','Chicken cesar','',700,1,0),
  ('salad-season','salad','Season','',500,1,0),
  ('salad-crab','salad','Crab','',600,1,0),
  ('salad-tuna','salad','Tuna','',600,1,0),
  ('platter-chicken','platter','Chicken','Ingredients ( garlic, fries , and salad)',900,1,1),
  ('platter-roasto','platter','Roasto','Ingredients ( sauce, fries , and salad)',900,1,1),
  ('platter-sawda-djej','platter','Sawda djej','Ingredients ( sauce, fries , and salad)',900,1,1),
  ('platter-kafta','platter','Kafta','Ingredients ( sauce, fries , and salad)',900,1,1),
  ('platter-kafta-cheese','platter','Kafta & cheese','Ingredients ( sauce, fries , and salad)',1000,1,1),
  ('platter-cocktaillo','platter','Cocktaillo','Ingredients ( sauce, fries , and salad, baby rocca)',1200,1,1),
  ('platter-fahita','platter','Fahita','Ingredients ( sauce, fries , and salad baby rocca)',1000,1,1),
  ('platter-burger-lebanese','platter','Burger lebanese','Ingredients ( sauce, fries , and salad)',900,1,1),
  ('platter-classic-cheese-burger','platter','Classic cheese burger','Ingredients ( sauce, fries , cheese, and salad)',1000,1,1),
  ('platter-chicken-burger','platter','Chicken burger','Ingredients ( sauce, fries , and salad)',900,1,1),
  ('platter-zinger','platter','Zinger','Ingredients ( sauce, fries , and salad)',900,1,1),
  ('platter-crispy-6pcs','platter','Crispy 6pcs','Ingredients ( sauce, fries , and salad)',1100,1,1),
  ('platter-cheesy-steak','platter','Cheesy steak','Ingredients ( sauce, fries , and rocca salad)',1200,1,1),
  ('platter-tawouk','platter','Tawouk','Ingredients ( sauce, fries , and salad)',900,1,1),
  ('platter-escalope-3pcs','platter','Escalope 3pcs','Ingredients ( sauce, fries , and salad)',1000,1,1);
