"use client";

import { FormEvent,useEffect,useMemo,useState } from "react";
type Role="manager"|"cashier"|"waiter";type User={id:string;name:string;role:Role};type MenuItem={id:string;name_en:string;name_ar:string;price_cents:number;category:string;addons_enabled:boolean};type Addon={id:string;name_en:string;name_ar:string};type Boot={user:User;menu:MenuItem[];addons:Addon[]};type CartLine={key:string;menuItemId:string;quantity:number;addonIds:string[]};type Receipt={order_number:number;table_name:string;cashier:string;subtotal_cents:number;subtotal_lbp:number;total_equivalent_cents:number;items:Array<{id:string;name_en:string;quantity:number;line_total_cents:number;addons:Array<{name_en:string;quantity:number;price_lbp:number}>}>};
const TOKEN_KEY="cocktaillio-session";const money=(c:number)=>`$${(c/100).toFixed(2)}`;const addonPrice=(id:string)=>{const n=Number(id.match(/(\d+)$/)?.[1]??0);return n<=9?100000:80000};
async function api<T>(path:string,init:RequestInit={}){const token=localStorage.getItem(TOKEN_KEY);const r=await fetch(path,{...init,cache:"no-store",headers:{...(init.body?{"Content-Type":"application/json"}:{}),...(token?{Authorization:`Bearer ${token}`}:{})}});const p=await r.json().catch(()=>({})) as T&{error?:string};if(!r.ok)throw new Error(p.error||`HTTP ${r.status}`);return p;}
export default function CounterPage(){
 const[boot,setBoot]=useState<Boot|null>(null),[error,setError]=useState(""),[username,setUsername]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[category,setCategory]=useState(""),[cart,setCart]=useState<CartLine[]>([]),[editing,setEditing]=useState<MenuItem|null>(null),[addons,setAddons]=useState<string[]>([]),[orderType,setOrderType]=useState<"takeaway"|"delivery"|"self_service">("takeaway"),[usd,setUsd]=useState(""),[lbp,setLbp]=useState(""),[rate,setRate]=useState("89500"),[customer,setCustomer]=useState(""),[phone,setPhone]=useState(""),[address,setAddress]=useState(""),[receipt,setReceipt]=useState<Receipt|null>(null);
 const load=async()=>{try{const d=await api<Boot>("/api/service/bootstrap");if(d.user.role==="waiter")throw new Error("Waiter uses Tables only.");setBoot(d);if(!category&&d.menu[0])setCategory(d.menu[0].category);setError("")}catch(e){setBoot(null);if(localStorage.getItem(TOKEN_KEY))setError(e instanceof Error?e.message:"Load failed")}};
 useEffect(()=>{void load()},[]);
 const login=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{const r=await api<{token:string}>("/api/auth/login",{method:"POST",body:JSON.stringify({username,password})});localStorage.setItem(TOKEN_KEY,r.token);await load()}catch(e){setError(e instanceof Error?e.message:"Login failed")}finally{setBusy(false)}};
 const cats=useMemo(()=>[...new Set(boot?.menu.map(i=>i.category)??[])],[boot]);const menu=boot?.menu.filter(i=>i.category===category)??[];
 const baseCents=cart.reduce((s,l)=>{const i=boot?.menu.find(x=>x.id===l.menuItemId);return s+(i?.price_cents??0)*l.quantity},0);const addonLbp=cart.reduce((s,l)=>s+l.addonIds.reduce((a,id)=>a+addonPrice(id)*l.quantity,0),0);const totalEq=baseCents+Math.round(addonLbp/Math.max(1,Number(rate))*100);
 const addItem=(i:MenuItem)=>{if(i.addons_enabled){setEditing(i);setAddons([])}else setCart(c=>[...c,{key:crypto.randomUUID(),menuItemId:i.id,quantity:1,addonIds:[]}])};
 const pay=async()=>{if(!cart.length)return;setBusy(true);try{const r=await api<{receipt:Receipt}>("/api/counter/orders",{method:"POST",body:JSON.stringify({orderType,items:cart.map(l=>({menuItemId:l.menuItemId,quantity:l.quantity,addons:l.addonIds.map(addonId=>({addonId,quantity:1}))})),usdCents:Math.round(Number(usd||0)*100),lbpAmount:Math.round(Number(lbp||0)),exchangeRateLbpPerUsd:Math.round(Number(rate||89500)),customerName:customer,phone,address})});setReceipt(r.receipt);setCart([]);setUsd("");setLbp("");setCustomer("");setPhone("");setAddress("")}catch(e){setError(e instanceof Error?e.message:"Checkout failed")}finally{setBusy(false)}};
 if(!boot)return <main className="counterLogin"><form onSubmit={login}><h1>Counter POS</h1><p>Manager / Cashier</p><input placeholder="Username" value={username} onChange={e=>setUsername(e.target.value)}/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<b>{error}</b>}<button disabled={busy}>Sign in</button></form><Style/></main>;
 return <main className="counter"><section className="mode"><button className={orderType==="takeaway"?"on":""} onClick={()=>setOrderType("takeaway")}>Takeaway</button><button className={orderType==="delivery"?"on":""} onClick={()=>setOrderType("delivery")}>Delivery</button><button className={orderType==="self_service"?"on":""} onClick={()=>setOrderType("self_service")}>Self Service · Bar</button></section>{error&&<div className="err">{error}</div>}
 <section className="counterLayout"><div className="catalog"><div className="cats">{cats.map(c=><button key={c} className={category===c?"on":""} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="items">{menu.map(i=><button key={i.id} onClick={()=>addItem(i)}><strong>{i.name_en}</strong><small>{i.name_ar}</small><b>{money(i.price_cents)}</b></button>)}</div></div><aside><h2>{orderType==="self_service"?"Self Service":orderType==="delivery"?"Delivery":"Takeaway"}</h2>{orderType==="delivery"&&<div className="delivery"><input placeholder="Customer name" value={customer} onChange={e=>setCustomer(e.target.value)}/><input placeholder="Phone" value={phone} onChange={e=>setPhone(e.target.value)}/><textarea placeholder="Address" value={address} onChange={e=>setAddress(e.target.value)}/></div>}<div className="cart">{cart.map(l=>{const i=boot.menu.find(x=>x.id===l.menuItemId)!;return <div className="row" key={l.key}><div><strong>{i.name_en}</strong>{l.addonIds.map(id=>{const a=boot.addons.find(x=>x.id===id);return <small key={id}>+ {a?.name_en} · {addonPrice(id).toLocaleString()} LBP</small>})}</div><div><button onClick={()=>setCart(c=>c.map(x=>x.key===l.key?{...x,quantity:Math.max(1,x.quantity-1)}:x))}>−</button><b>{l.quantity}</b><button onClick={()=>setCart(c=>c.map(x=>x.key===l.key?{...x,quantity:x.quantity+1}:x))}>+</button><button onClick={()=>setCart(c=>c.filter(x=>x.key!==l.key))}>×</button></div></div>})}</div><div className="tot"><span>Items</span><b>{money(baseCents)}</b></div>{addonLbp>0&&<div className="tot"><span>Add-ons</span><b>{addonLbp.toLocaleString()} LBP</b></div>}<div className="tot grand"><span>Total equivalent</span><b>{money(totalEq)}</b></div><div className="payment"><input placeholder="USD paid" value={usd} onChange={e=>setUsd(e.target.value)}/><input placeholder="LBP paid" value={lbp} onChange={e=>setLbp(e.target.value)}/><input placeholder="Rate" value={rate} onChange={e=>setRate(e.target.value)}/><button disabled={busy||!cart.length} onClick={()=>void pay()}>Pay · Send · Print Receipt</button></div></aside></section>
 {editing&&<div className="modal"><div className="addonBox"><h2>{editing.name_en}</h2><div className="addonGrid">{boot.addons.map(a=><button key={a.id} className={addons.includes(a.id)?"on":""} onClick={()=>setAddons(s=>s.includes(a.id)?s.filter(x=>x!==a.id):[...s,a.id])}><strong>{a.name_en}</strong><small>{a.name_ar}</small><b>{addonPrice(a.id).toLocaleString()} LBP</b></button>)}</div><div className="actions"><button onClick={()=>setEditing(null)}>Cancel</button><button onClick={()=>{setCart(c=>[...c,{key:crypto.randomUUID(),menuItemId:editing.id,quantity:1,addonIds:addons}]);setEditing(null)}}>Add item</button></div></div></div>}
 {receipt&&<div className="modal"><div className="receipt"><h2>Cocktaillo</h2><p><span>{receipt.table_name}</span><b>#{receipt.order_number}</b></p>{receipt.items.map(l=><p key={l.id}><span>{l.quantity} × {l.name_en}</span><b>{money(l.line_total_cents)}</b></p>)}<hr/><p><span>USD items</span><b>{money(receipt.subtotal_cents)}</b></p>{receipt.subtotal_lbp>0&&<p><span>Add-ons</span><b>{receipt.subtotal_lbp.toLocaleString()} LBP</b></p>}<p><span>Total</span><b>{money(receipt.total_equivalent_cents)}</b></p><small>Cashier: {receipt.cashier}</small><div className="actions"><button onClick={()=>window.print()}>Print</button><button onClick={()=>setReceipt(null)}>Close</button></div></div></div>}<Style/></main>
}
function Style(){return <style jsx global>{`*{box-sizing:border-box}body{margin:0;background:#f3f5f2;color:#173b2b;font-family:Arial,sans-serif}.counter{padding:12px}.mode{display:flex;gap:8px;margin-bottom:10px}.mode button,.cats button{border:1px solid #d5dfd8;background:#fff;border-radius:10px;padding:10px 13px;font-weight:800}.mode .on,.cats .on{background:#123f2b;color:#fff}.counterLayout{display:grid;grid-template-columns:1fr 360px;gap:12px}.catalog,aside{background:#fff;border:1px solid #dce5df;border-radius:15px;padding:12px}.cats{display:flex;gap:7px;overflow:auto;margin-bottom:10px}.items{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.items>button{min-height:82px;text-align:left;border:1px solid #dbe4de;background:#fff;border-radius:11px;padding:10px}.items strong,.items small,.items b{display:block}.items small{font-size:10px;color:#78867d;margin:4px 0}.cart{display:grid;gap:7px}.row{border:1px solid #e1e8e3;border-radius:10px;padding:9px;display:flex;justify-content:space-between;gap:8px}.row small{display:block;color:#6e7d73;font-size:10px}.row>div:last-child{display:flex;align-items:center;gap:4px}.row button{width:28px;height:28px}.tot{display:flex;justify-content:space-between;margin-top:9px}.grand{padding-top:9px;border-top:1px solid #e2e9e4}.payment,.delivery{display:grid;gap:7px;margin-top:10px}.payment input,.delivery input,.delivery textarea{padding:10px;border:1px solid #d4dfd7;border-radius:9px}.payment button{padding:12px;border:0;border-radius:10px;background:#123f2b;color:#fff;font-weight:800}.modal{position:fixed;inset:0;background:#10271db8;display:grid;place-items:center;padding:16px;z-index:1100}.addonBox,.receipt,.counterLogin form{width:min(620px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:16px;padding:18px}.addonGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.addonGrid button{border:1px solid #d9e3dc;background:#fff;border-radius:10px;padding:9px;text-align:left}.addonGrid .on{background:#123f2b;color:#fff}.addonGrid small,.addonGrid b{display:block;font-size:10px;margin-top:3px}.actions{display:flex;justify-content:flex-end;gap:7px;margin-top:12px}.actions button{padding:9px 12px}.receipt p{display:flex;justify-content:space-between}.counterLogin{min-height:100vh;display:grid;place-items:center}.counterLogin form{display:grid;gap:8px;max-width:380px}.counterLogin input,.counterLogin button{padding:11px}.err{background:#fee;color:#900;padding:9px;border-radius:9px;margin-bottom:8px}@media(max-width:800px){.counterLayout{grid-template-columns:1fr}.items{grid-template-columns:repeat(2,1fr)}aside{order:-1}.mode{overflow:auto}.mode button{white-space:nowrap}.addonGrid{grid-template-columns:repeat(2,1fr)}}`}</style>}
